Navbar and Hero Banner Created
Bismay5467/ExamArchive pull request #4
Opened 2024-04-29 20:53 UTC by simply-arko

The components are not responsive as of now, but they 'll be. Also theming is working but dark colour designs for individual components are not decided yet!
> Several packages  are added for Shad Cn and Acerternity UI.

2024-04-30 07:53 UTC, Bismay5467 requested changes

2024-04-30 07:53 UTC, Bismay5467 commented on client/src/components/theme-provider.tsx
Create separate files under "type" folder for declaring global types and interfaces.
Create separate files under "context" folder for declaring different contexts
Create separate files under "hooks" folder for declaring different hooks

2024-04-30 07:53 UTC, Bismay5467 commented on client/src/pages/Home/HeroBanner.tsx
> +const ChatBox: React.FC<chatBoxComp> = ({
Try to use functional declarations for components and functional expressions for utility functions - good coding practices :)

2024-04-30 07:53 UTC, Bismay5467 commented on client/src/pages/Home/HeroBanner.tsx
> +const HeroBanner = () => {
Single File Single Responsibility
Also try to separate logic from rendering to adhere to coding practices.

2024-04-30 20:36 UTC, ghost commented on client/src/components/theme-provider.tsx
@Bismay5467 I've created the folders and refactored the code as per suggestions. Please have a look!

2024-05-01 03:49 UTC, Bismay5467 requested changes
@simply-arko left some minor nits, nothing major. Once we get those cleaned up, we can get this PR merged in!!

2024-05-01 03:49 UTC, Bismay5467 commented on client/src/pages/Home/HeroBanner/HeroBanner.tsx
> +          <ChatBox
Avoid rendering same components multiple times. Grab all props in an array (array of props) and just map over that array.

2024-05-01 03:49 UTC, Bismay5467 commented on client/src/pages/Home/HeroBanner/ChatBox.tsx
> +  if (top) styleAttributes.top = top;
May refactor the code to something similar to this :

const styleAttributes = {
  ...(top && { top }),
  ...(bottom && { bottom }),
  ...(left && { left }),
  ...(right && { right }),
  backgroundColor: bgColor,
  color: textColor,
  'border-radius': borderRadius
};

2024-05-01 03:49 UTC, Bismay5467 commented on client/src/hooks/theme-provider.tsx
> +import React, { createContext, useContext, useEffect, useState } from 'react';
This file may later needs refactoring but for now LGTM!

2024-05-01 04:33 UTC, ghost commented
@Bismay5467 I've refactored the codebase as suggested. Please have a look!

2024-05-01 04:36 UTC, Bismay5467 approved these changes

2024-05-01 04:37 UTC, merged